### ISSUE TITLE
When running on aarch64, the wrong dotnet downloads are installed

### ISSUE THREAD

**Issue by lynnroth** [pjgpetecodes/dotnet5pi#5]
Thanks for providing this install script.  It definitely makes things easier.

When running the install.sh script on Raspberry Pi OS 64bit version, the 32 bit versions are installed, which seems to work but running dotnet gives an error:
dotnet: error while loading shared libraries: libstdc++.so.6

I changed the arm32 to arm64 in the download path and the script seems to work fine.

**Comment by pjgpetecodes** [comment]
Thanks for reporting Lynn! Hey @MarkXA... Any ideas on this one by any chance?

**Comment by strafe** [comment]
@pjgpetecodes something like this should work. On the 4B `uname -m` will return `aarch64`. Whereas on a 3B+ it will return `armv7l` (other earlier variants return `armv6l`, etc.).
```bash
arch() {
    if command -v uname > /dev/null; then
        cpu=$(uname -m)
        case $cpu in
        armv*l)
            echo "arm32"
            return 0
            ;;
        aarch64)
            echo "arm64"
            return 0
            ;;
        esac
    fi

    # Default to arm32?
    echo "arm32"
    return 0
}
```
